INFO:root:12:18:42 2020-07-11
INFO:root:Login.
INFO:root:Status code: 200
INFO:root:Session id: A62BA52E4C6BE15EF4A9E438094A9078.prod_a_113_4
WARNING:django.request:Not Found: /
INFO:root:12:19:21 2020-07-11
INFO:root:Login.
INFO:root:Status code: 200
INFO:root:Session id: F23BE80C2AB0A754D1DCEEC5C1C991CE.prod_a_113_4
ERROR:django.request:Internal Server Error: /portfolio/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/leopoldpfeiffer/PycharmProjects/degiro/degiro/portfolio/views.py", line 21, in get
    update_price_database()
  File "/Users/leopoldpfeiffer/PycharmProjects/degiro/degiro/portfolio/views.py", line 189, in update_price_database
    yahoo_df = get_yahoo_data(non_existing_symbols, start=start_date, end=end_date)
  File "/Users/leopoldpfeiffer/PycharmProjects/degiro/degiro/portfolio/lib/yahoodata.py", line 15, in get_yahoo_data
    currencies = {ticker: yf.Ticker(ticker).info['currency'] for ticker in tickers}
  File "/Users/leopoldpfeiffer/PycharmProjects/degiro/degiro/portfolio/lib/yahoodata.py", line 15, in <dictcomp>
    currencies = {ticker: yf.Ticker(ticker).info['currency'] for ticker in tickers}
  File "/usr/local/lib/python3.7/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/usr/local/lib/python3.7/site-packages/yfinance/base.py", line 415, in get_info
    self._get_fundamentals(proxy)
  File "/usr/local/lib/python3.7/site-packages/yfinance/base.py", line 286, in _get_fundamentals
    self._institutional_holders = holders[1]
IndexError: list index out of range
